#spring.application.name=department
#server.port=8081

spring:
  application:
    name: department
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
server:
  port: 8082
